export const FONTS = {
  interBlack: 'Inter-Black',
  interBold: 'Inter-Bold',
  interSemiBold: 'Inter-SemiBold',
  interRegular: 'Inter-Regular',
  interExtraLight: 'Inter-ExtraLight',
  arialBlack: 'Arial Black',
  interMedium: 'Inter-Medium',
  romanescoRegular: 'Romanesco-Regular',
  sahityaBold: 'Sahitya-Bold',
  sahityaRegular: 'Sahitya-Regular',
  robotoLight: 'Roboto-Light',
  robotoMedium: 'Roboto-Medium',
  robotoRegular: 'Roboto-Regular',
  robotoSemiBold: 'RobotoSlab-Bold',
  robotoSlabBold: 'RobotoSlab-Bold',
};